print('Numele_prenumele: Gutu Alexei')
print('anul_nasterii: 03.12.2004')
print('locul_nasterii: Chisinau')
print('e-mail: alexei.gutu321@mail.ru')
print('codul_postal: 3100')
print('nr_de_telefon: 069437009')
print('adresa: Smolian17/2')
print('nationalitatea: moldovan')
print('necasatorit')
print('studii: I.P.L.T,,Mihai Eminescu,clasa a 10 A')
print('limbele_studiate: limba engleaza,limba germana')
print('hobby:inotul,fotbalul')